-- MySQL Script generated by MySQL Workbench
-- ma 29 sep 2025 10:36:40 CEST
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`gamer`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`gamer` (
  `username` INT NOT NULL AUTO_INCREMENT,
  PRIMARY KEY (`username`),
  UNIQUE INDEX `username_UNIQUE` (`username` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`game`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`game` (
  `idgames` INT NOT NULL AUTO_INCREMENT,
  `achievements` VARCHAR(45) NULL,
  PRIMARY KEY (`idgames`),
  UNIQUE INDEX `idgames_UNIQUE` (`idgames` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`gamer_has_game`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`gamer_has_game` (
  `gamer_username` INT NOT NULL,
  `game_idgames` INT NOT NULL,
  `achievements gehaald` VARCHAR(45) NULL,
  PRIMARY KEY (`gamer_username`, `game_idgames`),
  INDEX `fk_gamer_has_game_game1_idx` (`game_idgames` ASC) VISIBLE,
  INDEX `fk_gamer_has_game_gamer_idx` (`gamer_username` ASC) VISIBLE,
  CONSTRAINT `fk_gamer_has_game_gamer`
    FOREIGN KEY (`gamer_username`)
    REFERENCES `mydb`.`gamer` (`username`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_gamer_has_game_game1`
    FOREIGN KEY (`game_idgames`)
    REFERENCES `mydb`.`game` (`idgames`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
